export default [
  'I should worry more',
  'I should worry less',
  "What's for breakfast?",
  "I'm scared of growing up",
  'I need help',
  'Will you help me?',
  "I'm not good enough",
  "I'm good enough",
  'I hope my pet misses me',
  'I still love you',
  'I hate communal transport',
  "I hope you're happy",
  'I am happy',
  'Did I turn off the stove?',
  'I wish I was a dolphin',
  'I should call my mom',
  'I miss my dad',
  'Pizza, again',
  'I deserve it',
  "I don't deserve it",
  'When will it stop?',
  'Bored out of my mind',
  'I should experience more',
  "Don't rush things",
  "I'm running out of time",
  'What am I doing with my life?',
  'Is that all there is?',
  'One step at a time',
  'How do I tie a tie?',
  "I'm proud of you",
  "I'm not ready",
  "I'm ready",
  'I can be better',
  'Pavlov probably thought about feeding his dogs every time someone rang a bell',
]
